### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by paulsch1975** [xbgmsharp/piwigo-forecast#1]
Hi,
I get a fatal Error when i use the plugin.

`Fatal error: Cannot use object of type stdClass as array in /var/www/vhosts/xxxxxxxxxx/httpdocs/piwigo/plugins/forecast/lib/forecast.io.php on line 177`

Please can you help me to fix the problem?
Thx
Paulsch

**Comment by xbgmsharp** [comment]
Hi,

Does you content has lat and long details? Looks like the return data is invalid.
Would you be able to dump the Lat,Long and timestamp?
You can run the SQL query from https://github.com/xbgmsharp/piwigo-forecast/blob/master/picture.inc.php#L125

**Comment by paulsch1975** [comment]
Hi,
yes the Content has lat and long details. I use the gmaps plugin without any problems.
If you want i can give you the Login Data to my Site.
Thanks
Paulsch

**Comment by xbgmsharp** [comment]
Yes please send the details by email. I need to get the data and reproduce the issue.

**Comment by paulsch1975** [comment]
where can i send the login details?? I dont want to post it here. if you want you can register on my site and i set you manually as webmaster. http://gallery.zboril.biz/register
THX
Paulsch

**Comment by xbgmsharp** [comment]
Please send me the data dump (lat, long, timestamp) by email. It is in the code source.
Or provide by email the login details to your gallery.
I need to be able to reproduce the issue in order to fix it.

**Comment by rarawls** [comment]
I have the same issue.  It happens to every picture with a lat/long.  If I hit refresh, it works just fine.  The next page I load breaks again.

_Piwigo 2.7.4
Operating system: Ubuntu Server 14.04
PHP: 5.5.9-1ubuntu4.9 (Show info) [2015-06-27 19:20:01]_

**Comment by xbgmsharp** [comment]
Could you please  run this SQL query:
`SELECT latitude,longitude,UNIX_TIMESTAMP(date_creation) as date FROM piwigo_images WHERE id = 'XX';
`
Where XX is the image ID and where IMAGES_TABLE must be replace by the actual table name (eg : piwigo_images).  I am wondering if the image does have a `date_creation` field.
https://github.com/xbgmsharp/piwigo-forecast/blob/master/picture.inc.php#L125

I will release an update soon and I would like to fix this issue before.

**Comment by rarawls** [comment]
```
+-----------+-------------+------------+
| latitude  | longitude   | date       |
+-----------+-------------+------------+
| 35.608014 | -120.656879 | 1411685412 |
+-----------+-------------+------------+
```

Thanks for looking into this.  I love the plug-in.  What else could I provide that would be helpful?

**Comment by xbgmsharp** [comment]
I tested with your input and the API proxy return the correct data. 
Thanks, glad you like.
I am currently working on a new release. See below the screenshot.
Would you be able to test it prior to the release and feedback? I hope to publish the new code today.
![screen shot 2015-07-01 at 10 32 37 am](https://cloud.githubusercontent.com/assets/1498985/8451680/e3142c62-1fdc-11e5-9917-9f568d21c30d.png)
![screen shot 2015-07-01 at 10 32 44 am](https://cloud.githubusercontent.com/assets/1498985/8451681/e3188744-1fdc-11e5-8437-585b109f0916.png)

**Comment by cavaliernavyman** [comment]
I'd be happy to.

**Comment by xbgmsharp** [comment]
Found the bug in the proxy. A dummy one, on the first call the data was not in an array.
It is fixed now.

**Comment by xbgmsharp** [comment]
Please update the plugin from the source on GitHub and feedback.
https://github.com/xbgmsharp/piwigo-forecast#installation
You will need to `Restore` the settings from the PWG admin panel.
There is still work to be done on the CSS but I believe it is nice release.
Let me know.

**Comment by xbgmsharp** [comment]
I release a new version 2.7.b
I am closing the issue as the fatal error when using the proxy is fixed.
Please feedback.
