### ISSUE TITLE
Reflect Dark Sky Rebranding

### ISSUE THREAD

**Issue by KennyStier** [xbgmsharp/piwigo-forecast#10]
Forecast.io "unified" their brand and they now use their app's name "Dark Sky" instead.
The API URL has changed too, and the old API URL will be defunct at the end of the year.
http://blog.darksky.net/introducing-darksky-net/

**Comment by xbgmsharp** [comment]
Done in release v2.8.b, I still have to update the proxy.

**Comment by KennyStier** [comment]
Looks Great!
