### ISSUE TITLE
Overlay Issue

### ISSUE THREAD

**Issue by rarawls** [xbgmsharp/piwigo-forecast#3]
Thanks for the quick fix on the previous issue.  I apologize for my lack of correspondence; I was traveling.  In any case, I grabbed the latest and found a slight problem with the formatting.  It looks the same using both Firefox and Midori.

![First Image](http://oi58.tinypic.com/2ewdv5u.jpg)
![First Image](http://oi58.tinypic.com/2h6ynfp.jpg)

That said, I really like the latest release!

**Comment by xbgmsharp** [comment]
Which template are you using?

**Comment by rarawls** [comment]
2.7.b from the piwigo plug-in installation page.  Is that what you mean?

**Comment by xbgmsharp** [comment]
No this is the plugin version.
I mean which theme/template.
Do you use the default one or a different one?

**Comment by rarawls** [comment]
I suppose that would be a "duh!" moment...  I'm using the "clear" theme and nothing specific is selected under templates so I assume all defaults.

**Comment by xbgmsharp** [comment]
The "clear" theme is not the default. It is "elegant".
It is hard to make it prefect for all themes. You could edit the CSS forecast.css on Line 151
https://github.com/xbgmsharp/piwigo-forecast/blob/master/lib/forecast.css#L151

**Comment by rarawls** [comment]
The largest value that worked for both themes (default/elegant and clear) was 18.  I'm happy living with the hack on my site, but it might be best to use the value which works in the most cases.  

Thanks for time and help.

**Comment by xbgmsharp** [comment]
OK will change the value to:

> font-size: 18px;
>  text-align: center;
