### ISSUE TITLE
Forecast is Crammed, Doesn't Fit

### ISSUE THREAD

**Issue by KennyStier** [xbgmsharp/piwigo-forecast#9]
For some reason, the forecast given in the Info section
https://icgallery.flexstart.me/picture.php?/27/category/3 (hidden in sidebar)
is very crammed and when expanded just flows everywhere and doesn't stay in place. What can I do to give the forecast section ample space? Is this a bug?

**Comment by xbgmsharp** [comment]
The plugin is develop with the default PWG template.  As per https://github.com/xbgmsharp/piwigo-forecast/issues/3
The "clear" theme is not the default. It is "elegant". It is hard to make it prefect for all themes. 
Not sure what is the best way to allow multiple template layout.

You could edit the CSS forecast.css on Line 152 and uncomment ``text-align: left;``
```
#forecast-info .section h2 {
text-align: left;
```
on Line82 comment ``position: absolute;``
```
#forecast-info .section.currently .current_container .more .table {
position: absolute;
```

**Comment by xbgmsharp** [comment]
So to make it nicer.
You could edit the CSS forecast.css:
- On Line 48 and replace ```width: 280px;``` with ```width: 100%;```.
- Add a line 117, ```color: rgb(51, 51, 51)```
- On Line 82 comment ``position: absolute;``

**Comment by xbgmsharp** [comment]
Release v2.8.b that should improve template support.
Please test and report if any better.

**Comment by KennyStier** [comment]
The new release is much better! Thanks so much!
It still doesn't look perfect on my specific theme, but with a little tweak to my theme it looks great!

If anyone is having troubles with using this plugin on a certain theme, Text mode works very well!
